@CodeReview.UsersBFF.Api_HostAddress = http://localhost:5290

### Register a new user
POST {{CodeReview.UsersBFF.Api_HostAddress}}/users/register
Content-Type: application/json
Accept: application/json

{
  "email": "milena@example.com",
  "firstName": "Milena",
  "lastName": "Popovic",
  "password": "P@ssw0rd123!"
}

### Register a new user - error
POST {{CodeReview.UsersBFF.Api_HostAddress}}/users/register
Content-Type: application/json
Accept: application/json

{
  "email": "",
  "firstName": null,
  "lastName": "Popovic",
  "password": "P@ssw0rd123!"
}


### docker container testing 
@port = 8080
@host = localhost

# POST Register a new user
POST http://{{host}}:{{port}}/users/register
Content-Type: application/json
Accept: application/json

{
    "email": "milena@example.com",
    "firstName": "Milena",
    "lastName": "Popovic",
    "password": "P@ssw0rd123!"
}




